export const getStackImageUrl = (stack: string) => {
  const data: {[key: string]: string} = {
    JavaScript: 'https://skillicons.dev/icons?i=js',
    TypeScript: 'https://skillicons.dev/icons?i=ts',
    React: 'https://skillicons.dev/icons?i=react',
    Vue: 'https://skillicons.dev/icons?i=vue',
    Nextjs: 'https://skillicons.dev/icons?i=nextjs',
    Nodejs: 'https://skillicons.dev/icons?i=nodejs',
    Spring: 'https://skillicons.dev/icons?i=spring',
    Java: 'https://skillicons.dev/icons?i=java',
    Nestjs: 'https://skillicons.dev/icons?i=nestjs',
    Express: 'https://skillicons.dev/icons?i=express',
    Go: 'https://skillicons.dev/icons?i=go',
    C: 'https://skillicons.dev/icons?i=c',
    Python: 'https://skillicons.dev/icons?i=py',
    Django: 'https://skillicons.dev/icons?i=django',
    Swift: 'https://skillicons.dev/icons?i=swift',
    Kotlin: 'https://skillicons.dev/icons?i=kotlin',
    MySQL: 'https://skillicons.dev/icons?i=mysql',
    MongoDB: 'https://skillicons.dev/icons?i=mongodb',
    php: 'https://skillicons.dev/icons?i=php',
    GraphQL: 'https://skillicons.dev/icons?i=graphql',
    Firebase: 'https://skillicons.dev/icons?i=firebase',
    ReactNative: 'https://skillicons.dev/icons?i=react',
    Unity: 'https://skillicons.dev/icons?i=unity',
    Flutter: 'https://skillicons.dev/icons?i=flutter',
    AWS: 'https://skillicons.dev/icons?i=aws',
    Kubernetes: 'https://skillicons.dev/icons?i=kubernetes',
    Docker: 'https://skillicons.dev/icons?i=docker',
    Git: 'https://skillicons.dev/icons?i=git',
    Figma: 'https://skillicons.dev/icons?i=figma',
    Zeplin: 'https://skillicons.dev/icons?i=zeplin',
  };
  return data[stack] || '';
};
