export const getStackImageUrl = (stack: string) => {
  const data: {[key: string]: string} = {
    js: 'https://skillicons.dev/icons?i=js',
    ts: 'https://skillicons.dev/icons?i=ts',
    react: 'https://skillicons.dev/icons?i=react',
    vue: 'https://skillicons.dev/icons?i=vue',
    nextjs: 'https://skillicons.dev/icons?i=nextjs',
    nodejs: 'https://skillicons.dev/icons?i=nodejs',
    spring: 'https://skillicons.dev/icons?i=spring',
    java: 'https://skillicons.dev/icons?i=java',
    nestjs: 'https://skillicons.dev/icons?i=nestjs',
    express: 'https://skillicons.dev/icons?i=express',
    go: 'https://skillicons.dev/icons?i=go',
    c: 'https://skillicons.dev/icons?i=c',
    python: 'https://skillicons.dev/icons?i=py',
    django: 'https://skillicons.dev/icons?i=django',
    swift: 'https://skillicons.dev/icons?i=swift',
    kotlin: 'https://skillicons.dev/icons?i=kotlin',
    mysQL: 'https://skillicons.dev/icons?i=mysql',
    mongodb: 'https://skillicons.dev/icons?i=mongodb',
    php: 'https://skillicons.dev/icons?i=php',
    graphql: 'https://skillicons.dev/icons?i=graphql',
    firebase: 'https://skillicons.dev/icons?i=firebase',
    reactnative: 'https://skillicons.dev/icons?i=react',
    unity: 'https://skillicons.dev/icons?i=unity',
    flutter: 'https://skillicons.dev/icons?i=flutter',
    aws: 'https://skillicons.dev/icons?i=aws',
    kubernetes: 'https://skillicons.dev/icons?i=kubernetes',
    docker: 'https://skillicons.dev/icons?i=docker',
    git: 'https://skillicons.dev/icons?i=git',
    figma: 'https://skillicons.dev/icons?i=figma',
    zeplin: 'https://skillicons.dev/icons?i=zeplin',
  };
  return data[stack] || '';
};
