export const POSITIONS = [
  {label: '프론트엔드', value: '프론트엔드'},
  {label: '백엔드', value: '백엔드'},
  {label: '디자이너', value: '디자이너'},
  {label: 'IOS', value: 'IOS'},
  {label: '안드로이드', value: '안드로이드'},
  {label: '데브옵스', value: '데브옵스'},
  {label: 'PM', value: 'PM'},
  {label: '기획자', value: '기획자'},
];

export const CAREERS = [
  {label: '0년', value: '0년'},
  {label: '1년', value: '1년'},
  {label: '2년', value: '2년'},
  {label: '3년', value: '3년'},
  {label: '4년', value: '4년'},
  {label: '5년', value: '5년'},
  {label: '6년', value: '6년'},
  {label: '7년', value: '7년'},
  {label: '8년', value: '8년'},
  {label: '9년', value: '9년'},
  {label: '10년 이상', value: '10년 이상'},
];

export const STACKS = [
  {label: 'JavaScript', value: 'JavaScript'},
  {label: 'TypeScript', value: 'TypeScript'},
  {label: 'React', value: 'React'},
  {label: 'Vue', value: 'Vue'},
  {label: 'Nextjs', value: 'Nextjs'},
  {label: 'Nodejs', value: 'Nodejs'},
  {label: 'Spring', value: 'Spring'},
  {label: 'Java', value: 'Java'},
  {label: 'Nestjs', value: 'Nestjs'},
  {label: 'Express', value: 'Express'},
  {label: 'Go', value: 'Go'},
  {label: 'C', value: 'C'},
  {label: 'Python', value: 'Python'},
  {label: 'Django', value: 'Django'},
  {label: 'Swift', value: 'Swift'},
  {label: 'Kotlin', value: 'Kotlin'},
  {label: 'MySQL', value: 'MySQL'},
  {label: 'MongoDB', value: 'MongoDB'},
  {label: 'php', value: 'php'},
  {label: 'GraphQL', value: 'GraphQL'},
  {label: 'Firebase', value: 'Firebase'},
  {label: 'ReactNative', value: 'ReactNative'},
  {label: 'Unity', value: 'Unity'},
  {label: 'Flutter', value: 'Flutter'},
  {label: 'AWS', value: 'AWS'},
  {label: 'Kubernetes', value: 'Kubernetes'},
  {label: 'Docker', value: 'Docker'},
  {label: 'Git', value: 'Git'},
  {label: 'Figma', value: 'Figma'},
  {label: 'Zeplin', value: 'Zeplin'},
];
